### ISSUE TITLE
Node-red Ntfy

### ISSUE THREAD

**Issue by joneyes** [camerahacks/rpilocator-rss-feed#12]
I'm a noob at this...

I want to use the node red flow to send updates via ntfy.
I though it would be simple to amend the http request node to post to ntfy, but when it runs i didnt get what i expected, I suspect the format in the function node is wrong, as I see this in ntfy:

> 11/12/2022, 15:59
> 
> {"type":"link","title":"xlocator Stock Alert","body":"Stock Alert (AT): RPi 4 Model B - 8GB RAM is In Stock at Semaf","url":"rpilocator.com?vendor=semaf&utm_source=feed&utm_medium=rss"}

Coding is definitely my weak point. Now if it was a bunch of components on a pcb, I could fix that, but I don't know where to start here...
Any help would be appreciated!

**Comment by camerahacks** [comment]
I have never used ntfy but based [on their docs](https://docs.ntfy.sh/publish/#publish-as-json), they accept plain text or JSON messages. The JSON has different components than Pushbullet's, so that's why you are just getting a JSON string in your ntfy notification.

So, you should be able to change the http request to post to ```https://ntfy.sh/``` and change the ```message``` variable in the function node to something like the below. This implies that your ntfy topic is called 'rpilocator'.

Let me know if this works for you.

```javascript
var message = {
        'topic': 'rpilocator',
        'message': entry.title[0],
        'title': MESSAGE_TITLE,
        'priority': 4,
        'actions': [{ 'action': 'view', 'label': 'rpilocator website', 'url': entry.link[0] }]
}
```

**Comment by joneyes** [comment]
Thank you, I've set it up, but I'm not seeing any output output yet - I guess i need to wait for a stock change alert somewhere.
From debug, I can see the xml output is being sent, but as nothing changes, nothing drops out of the Check new alerts function node.
Once I know it works, i'll amend the filters on the http request.

**Comment by joneyes** [comment]
I've confirmed that this now works.
Revised, test flow attached, which you can add to the files list.
[NTFY flows.zip](https://github.com/camerahacks/rpilocator-rss-feed/files/10209506/NTFY.flows.zip)

**Comment by camerahacks** [comment]
Could you do a Pull Request so I can add the ntfy flow?
